### ISSUE TITLE
Possibility to change the color of the shapes: rectangle, circle, arrow,...

### ISSUE THREAD

**Issue by simonbcn** [lupoDharkael/flameshot#16]
It would be very useful to add the possibility of changing the color of the figures: rectangle, circle, arrow,...

**Comment by lupoDharkael** [comment]
if you press Right Click in your mouse you can select the color of your draw tools. Actually they are fixed but I'd like to add the possibility of changing what colors appear in the color selection tool.

**Comment by simonbcn** [comment]
ok, thanks. 👍

**Comment by snakeru** [comment]
A note for anyone finding this ticket and still not understanding, how to do it:

YOU HAVE TO RIGHT-CLICK-AND-HOLD BEFORE TAKING THE SCREENSHOT.

**Comment by mmahmoudian** [comment]
@snakeru Actually since few versions ago, you don't need to hold, just right-click, then left-click on the color you want. But as you said the color should be selected before drawing.

**BUT** there is now (v0.10.1) a feature that let user to modify annotations after they have been drawn. Simply click on the tool button again to deselect it (if it is already selected), then left-click on the object you have drawn, then you can change the size by scrolling, change the color by right-click or from the left panel (press <kbd>space</kbd>), or move by dragging the object.

Enjoy taking screenshots
